apiVersion: console.openshift.io/v1
kind: ConsoleYAMLSample
metadata:
  name: eso-vault-secret-store-provider-sample
spec:
  description: An example Vault SecretStore using Kubernetes Authentication method.
    Documentation can be found at https://developer.hashicorp.com/vault/docs/auth/kubernetes
  targetResource:
    apiVersion: external-secrets.io/v1
    kind: SecretStore
  title: Example SecretStore - HashiCorp Vault Kubernetes Authentication
  yaml: |-
    apiVersion: external-secrets.io/v1
    kind: SecretStore
    metadata:
      name: SECRET_STORE_NAME
      namespace: SECRET_STORE_NAMESPACE
    spec:
      provider:
        vault:
          server: "http://VAULT_IP_ADDRESS:8200"
          path: "kv"
          version: "v2"
          auth:
            # Authenticate against Vault using a Kubernetes ServiceAccount
            # token stored in a Secret.
            # https://www.vaultproject.io/docs/auth/kubernetes
            kubernetes:
              # Path where the Kubernetes authentication backend is mounted in Vault
              mountPath: "kubernetes"
              # A required field containing the Vault Role to assume.
              role: VAULT_ROLE
              # Optional service account field containing the name
              # of a kubernetes ServiceAccount
              serviceAccountRef:
                name: SERVICE_ACCOUNT_NAME
                namespace: SERVICE_ACCOUNT_NAMESPACE
